contactapp/urls.py
from django.urls import path
from . import views

app_name = 'contactapp'
urlpatterns = [
    path('show_all/', views.contacts, name='show_all'),
    path('new_contact/', views.new_contact, name='new_contact'),
    path('<int:id>/update_contact/', views.update_contact, name='update_contact'),
    path('<int:id>/delete_contact/', views.delete_contact, name='delete_contact'),
]

formdemo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('contact/', include('contactapp.urls')),
    path('person/', include('personapp.urls')),
]

personapp/urls.py
from django.urls import path
from . import views

app_name = 'personapp'
urlpatterns = [
  path('show_all/', views.show_all, name='show_all'),
  path('new_person/', views.new_person, name='new_person'),
  path('<int:id>/update_person/', views.update_person, name='update_person'),
]

contactapp/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
  firstname = models.CharField(max_length=20)
  lastname = models.CharField(max_length=20)
  company = models.CharField(max_length=20)
  mobile = models.CharField(max_length=10)

  def __str__(self):
    return self.firstname

personapp/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
  firstname = models.CharField(max_length=30)
  lastname = models.CharField(max_length=30)
  email = models.EmailField(max_length=100)
  phone = models.CharField(max_length=20)
  bio = models.TextField(max_length=500)

  def __str__(self):
    return self.firstname

contactapp/forms.py
from django import forms
from django.core.validators import RegexValidator

def start_with_cap_letter(value):
  if str(value[0]).islower():
    raise forms.ValidationError('The text should startwith Capital Letter.')
  

class ContactForm(forms.Form):
  firstname = forms.CharField(label='Firstname', min_length=4, max_length=20,  widget=forms.TextInput(attrs={'class':'form-control'}), validators=[start_with_cap_letter,])
  lastname = forms.CharField(label='Lastname', min_length=4, max_length=20,  widget=forms.TextInput(attrs={'class':'form-control'}), validators=[start_with_cap_letter])
  company = forms.CharField(label='Company',  widget=forms.TextInput(attrs={'class':'form-control'}), validators=[start_with_cap_letter])
  mobile = forms.CharField(label='Mobile Phone', max_length=12, widget=forms.TextInput(attrs={'class':'form-control'}), 
                           validators=[RegexValidator('[0]\d[-]\d{4}[-]\d{4}',message='enter mobile number format 0x-xxxx-xxxx')])
  

personapp/forms.py
from django.forms import ModelForm, ValidationError
from django import forms
from .models import Person

class PersonForm(ModelForm):

  class Meta:
    model = Person
    fields = ('firstname', 'lastname', 'email', 'phone', 'bio')

    widgets = {
      'firstname':forms.TextInput(attrs={'class':'form-control'}),
      'lastname':forms.TextInput(attrs={'class':'form-control'}),
      'email':forms.TextInput(attrs={'class':'form-control'}),
      'phone':forms.TextInput(attrs={'class':'form-control'}),
      'bio':forms.Textarea(attrs={'class':'form-control'}),
    }

  
  def clean_firstname(self):
    firstname = self.cleaned_data['firstname']
    if len(str(firstname))<4:
      raise ValidationError('Firstname must be more than or equal to 4 characters')
    
    return firstname
  
  def clean_lastname(self):
    lastname = self.cleaned_data['lastname']
    if len(str(lastname))<4:
      raise ValidationError('Lastname must be more than or equal to 4 characters')
    
    return lastname
  
  
  
  
  
  

contactapp/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from .models import Contact
from django.contrib import messages

# Create your views here.
def contacts(request):
  contacts = Contact.objects.all()
  context = {
    'title': 'Show My Contacts',
    'contacts': contacts
  }
  return render(request, 'contact/show_all.html', context)

def new_contact(request): 
  
  if request.method == 'POST':
    form = ContactForm(request.POST)
    if form.is_valid():
      firstname = form.cleaned_data['firstname']
      lastname = form.cleaned_data['lastname']
      company = form.cleaned_data['company']
      mobile = form.cleaned_data['mobile']

      contact = Contact(firstname=firstname, lastname=lastname, company=company, mobile=mobile)
      contact.save()
      
      messages.success(request, 'Add New Contact Successfull.')
      return redirect(to='contactapp:show_all')
    
    else:
      pass

  else:
    form = ContactForm(None)
    

  return render(request, 'contact/new_contact.html', {'title':'New Contact', 'form':form})

def update_contact(request, id):
  contact = Contact.objects.get(pk=id)
  if request.method == 'POST':
    form = ContactForm(request.POST)
    if form.is_valid():
      contact.firstname = form.cleaned_data['firstname']
      contact.lastname = form.cleaned_data['lastname']
      contact.company = form.cleaned_data['company']
      contact.mobile = form.cleaned_data['mobile']

      contact.save()
      
      messages.success(request, 'Update Contact Successfully!')
      return redirect(to='contactapp:show_all')

  else:
    form = ContactForm(initial=
            {
              'firstname':contact.firstname,
              'lastname':contact.lastname,
              'company':contact.company,
              'mobile':contact.mobile,
              
            })

  context = {
    'title':'Update Contact',
    'form': form,
    
  }

  return render(request, 'contact/update_contact.html', context)

def delete_contact(request, id):
  contact = Contact.objects.get(pk=id)
  contact.delete()

  messages.success(request, 'Delete contact Successfully!')

  return redirect(to='contactapp:show_all')

formdemo/views.py
from django.shortcuts import render

def index(request):
  return render(request, 'index.html', {'title':'Home Page'})

personapp/views.py
from django.shortcuts import render, redirect
from .models import Person
from .forms import PersonForm
from django.contrib import messages

# Create your views here.
def show_all(request):
  persons = Person.objects.all()
  context = {
    'title':'Show All Persons',
    'persons': persons
  }
  return render(request, 'person/show_all.html', context) 

def new_person(request):
  if request.method == 'POST':
    form = PersonForm(request.POST)
    if form.is_valid():
      person = form.save(commit=True)
      person.save()

      messages.success(request, 'Add New Person Successfully!')
      return redirect(to='personapp:show_all')
  else:
    form = PersonForm()

  context = {
    'title': 'Add New Person',
    'form': form
  }
  return render(request, 'person/new_person.html', context)

def update_person(request, id):
  person = Person.objects.get(id=id)

  if request.method == 'POST':
    form = PersonForm(request.POST, instance=person)
    if form.is_valid():
      person = form.save(commit=True)
      person.save()
      messages.success(request, 'Update Person Successfully!')
      return redirect(to='personapp:show_all')
  else:
    form = PersonForm(instance=person)

  context = {
    'title':'Update Person',
    'form': form
  }
  return render(request, 'person/update_person.html', context)

templates/contact/new_contact.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    
    <div class="card mt-3 mb-4">
      <div class="card-header bg-success text-center text-light">
        <h4>{{title}}</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}

          <div class="mb-3">
            <label class="form-label">{{form.firstname.label}}</label>
            {% if form.errors %}
            {{form.firstname}}
            <div class="text-danger">
              {% for error in form.firstname.errors %}
                <span>{{error}}</span>
              {% endfor %}
            </div>
            
            {% else %}
            {{form.firstname}}
            {% endif %}
            
            
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.lastname.label}}</label>
            {{form.lastname}}
            <div class="text-danger">
              {% for error in form.lastname.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.company.label}}</label>
            {{form.company}}
            <div class="text-danger">
              {% for error in form.company.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.mobile.label}}</label>
            {{form.mobile}}
            <div class="text-danger">
              {% for error in form.mobile.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3 text-center mt-5">
            <button type="submit" class="btn btn-outline-success"><i class="bi bi-person-add"></i> New Contact</button>
          </div>
        </form>
      </div>
    </div>
    
  </div>
{% endblock %}

templates/contact/show_all.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    <div class="row">
      <div class="col-12">
        <a href="{% url 'contactapp:new_contact' %}" class="btn btn-outline-success float-end"><i class="bi bi-person-add"></i> Add New Contact</a>
      </div>
    </div>
    <div class="table-responsive mt-4">
      <div class="card">
        <div class="card-header bg-success text-center text-light">
          <h4>{{title}}</h4>
        </div>
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Company</th>
                <th>Mobile Phone</th>
                <th>Action</th>
              </tr>
            </thead>
            {% for contact in contacts %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{contact.firstname}}</td>
                <td>{{contact.lastname}}</td>
                <td>{{contact.company}}</td>
                <td>{{contact.mobile}}</td>
                <td>
                  <a href="{% url 'contactapp:update_contact' id=contact.id %}" class="btn btn-outline-success btn-sm"><i class="bi bi-person-check"></i></a>
                  <a onclick="return confirm('Are you sure to delete this contact?')" href="{% url 'contactapp:delete_contact' id=contact.id %}" class="btn btn-outline-danger btn-sm"><i class="bi bi-person-x"></i></a>
                </td>
              </tr>
            {% endfor %}
            
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/contact/update_contact.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    
    <div class="card mt-3 mb-4">
      <div class="card-header bg-success text-center text-light">
        <h4>{{title}}</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}

          <div class="mb-3">
            <label class="form-label">{{form.firstname.label_tag}}</label>
            {% if form.errors %}
            {{form.firstname}}
            <div class="text-danger">
              {% for error in form.firstname.errors %}
                <span>{{error}}</span>
              {% endfor %}
            </div>
            
            {% else %}
            {{form.firstname}}
            {% endif %}
            
            
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.lastname.label_tag}}</label>
            {{form.lastname}}
            <div class="text-danger">
              {% for error in form.lastname.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.company.label_tag}}</label>
            {{form.company}}
            <div class="text-danger">
              {% for error in form.company.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label">{{form.mobile.label_tag}}</label>
            {{form.mobile}}
            <div class="text-danger">
              {% for error in form.mobile.errors %}
                  <span>{{error}}</span>
              {% endfor %}
              
            </div>
          </div>
          <div class="mb-3 text-center mt-5">
            <button type="submit" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> Update Contact</button>
          </div>
        </form>
      </div>
    </div>
    
  </div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
  </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <title>Form Demo - {% block title %}{% endblock %}
  </title>
  <style>
    body{
      font-family: 'Itim', cursive;
    }
  </style>
</head>
<body>
  {% include "navbar.html" %}
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
      <strong>{{message}}!</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    
  {% endif %}
  
  
  {% block content %}{% endblock %}
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-success navbar-dark text-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">CTA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactapp:show_all' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'personapp:show_all' %}">Person</a>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>

templates/person/new_person.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    <div class="card mb-4">
      <div class="card-header bg-success text-center text-light">
        <h4>{{title}}</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}
          {% for field in form %}
          <div class="mb-3">
            <label class="form-label">{{field.label}}</label>
            {% if field.errors %}
            {{field}}
            
            <div class="text-danger">
              {% for error in field.errors %}
                <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %}
            {{field}}
            {% endif %}
            
            </div>
          {% endfor %}
          
          
          
          <button type="submit" class="btn btn-outline-success">{{title}}</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/person/show_all.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    <div class="row">
      <div class="col-12">
        <a href="{% url 'personapp:new_person' %}" class="btn btn-outline-success float-end">Add New Person</a>
      </div>
    </div>
    <div class="table-responsive mt-4">
      <div class="card">
        <div class="card-header bg-success text-center text-light">
          <h4>{{title}}</h4>
        </div>
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Mobile Phone</th>
                <th>Action</th>
              </tr>
            </thead>
            {% for person in persons %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{person.firstname}}</td>
                <td>{{person.lastname}}</td>
                <td>{{person.email}}</td>
                <td>{{person.phone}}</td>
                <td>
                  <a href="{% url 'personapp:update_person' id=person.id %}" class="btn btn-outline-success btn-sm">update</a>
                </td>
              </tr>
            {% endfor %}
            
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/person/update_person.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h3>{{title}}</h3>
    <hr>
    <div class="card mb-4">
      <div class="card-header bg-success text-center text-light">
        <h4>{{title}}</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}
          {% for field in form %}
          <div class="mb-3">
            <label class="form-label">{{field.label}}</label>
            {% if field.errors %}
            <div class="form-control">{{field}}</div>
            
            <div class="text-danger">
              {% for error in field.errors %}
                <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %}
            {{field}}
            {% endif %}
            
            </div>
          {% endfor %}
          
          
          <div class="mb-3 mt-4 text-center">
            <button type="submit" class="btn btn-outline-success">{{title}}</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>
{% endblock %}